version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: glass_task_db
    restart: always
    environment:
      MYSQL_DATABASE: sgc_pro
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/database.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: glass_task_backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=sgc_pro
      - PORT=3000
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: glass_task_frontend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  db_data:
